canonical/iam-bundle

.github/workflows/on_pull_request.yaml, .github/workflows/on_push.yaml, .github/workflows/publish.yaml
Bundle publishing on push failed. This PR fixes the action:
- install tox before bundle rendering
- correct logs location in logdump
- update actions/checkout to v3
- publish the bundle only if its template has changed - for example, when we change dependencies channel. Otherwise there is no need to keep publishing the same bundle
- insufficient charmcraft access was updated by adding a new secret.
=> fix: fixes publish job

.github/workflows/publish.yaml, bundle.yaml.j2
The job for publishing the bundle if its template has changed doesn't run because it references a path relative to the workflow file. This PR fixes it by changing it to absolute path.
=> Fix workflow for publishing bundle

.github/workflows/tests.yaml, README.md, integration-requirements.txt, manifests/dex.yaml, pyproject.toml, render_bundle.py, tests/integration/__init__.py, tests/integration/auth_utils.py, tests/integration/conftest.py, tests/integration/dex.py, tests/integration/test_bundle.py, tox.ini
Add end to end tests using dex and playwright. 
The scaling tests are commented out because both hydra and kratos logic is bugged:
1) The units don't share the secret that the apps use
2) Scaling up hydra sets the unit's status to maintenance without changing it back.
=> Add end-to-end tests

.github/workflows/publish.yaml, README.md, bundle.yaml.j2, tests/integration/test_bundle.py
This PR:
- renames the bundle from `iam` to `identity-platform`
- pins traefik to rev 136 due to issue with tls relation
- uses `ops_test.run` to deploy the bundle rather than `ops_test.model.deploy` due to a bug with ignoring pinned revision (https://github.com/charmed-kubernetes/pytest-operator/issues/111)
=> chore: rename bundle to identity-platform

bundle.yaml.j2
This pull request aims to pin down the charms' revisions. The revisions represent the latest charm versions that could be published.
=> IAM-449 pin down the charms revisions

bundle.yaml.j2
This pull request aims to bump the revisions of kratos and hydra charms.
- [kratos release](https://github.com/canonical/kratos-operator/releases/tag/rev353)
- [hydra release](https://github.com/canonical/hydra-operator/releases/tag/rev242)
=> bump: upgrade kratos and hydra charms

bundle_renderer.py
The `singledispatch` in `functools` does not respect the type annotation used from `typing` below Python 3.11. So put this fix to work around this issue.
=> fix: work around the singledispatch bug in lower python version

tests/integration/test_bundle.py
With the removal of the `dev` flag from Hydra, HTTP redirect URLs are not allowed. This changes the dummy client's redirect URI to HTTPS.
=> Make redirect URL HTTPS

integration-requirements.txt
Quick fix for the protobuf issue in the integration test.
=> fix: pinned macaroonbakery to 1.3.2

.github/workflows/publish.yaml, bundle.yaml.j2
Changed self-signed-certificates charm channel to latest/edge.
Changed charmcraft channel to latest/stable in the publish workflow.
=> Fixes for track/0.1

bundle.yaml.j2
This PR bumps the kratos revision to 393 to include a new `kratos-info` relation in the `latest/edge` version of the identity platform bundle.
rev390 -> 393 contains the following updates:
- Fix on_schedule workflow in https://github.com/canonical/kratos-operator/pull/177
- fix(loki-rule): improve error handling in json parsing n https://github.com/canonical/kratos-operator/pull/178
- Add kratos-info interface in https://github.com/canonical/kratos-operator/pull/179
=> chore: bump kratos rev

bundle.yaml.j2
Since traefik `latest/stable` [release](https://charmhub.io/traefik-k8s) now supports forward-auth, the revision can be unpinned.
=> chore: unpin traefik revision

.github/workflows/release.yaml, oauth_tools/__init__.py, pyproject.toml
Tested that the version is bumped correctly and that the ChangeLog is generated, not sure what the tag that will be created will look like (will it have the `oauth_tools` prefix?)
=> Add release-please for oauth_tools

oauth_tools/fixtures.py, oauth_tools/oauth_helpers.py
- If other apps were already deployed in the model, `deploy_identity_bundle` would wait for them as well
- Use `pytest_asyncio.fixture` for async fixtures
=> oauth_tools fixes

oauth_tools/dex.yaml
The mismatch in the namespace, caused by the extra quote, is causing permission issues in the dex container.
=> Remove the extra single quote character in the dex manifest

bundle.yaml.j2
This PR:
- bumps charm revisions to prepare for 0.3 bundle release
fixes https://github.com/canonical/iam-bundle/issues/268
=> chore: bump charm revisions

charmcraft.yaml
Since charmcraft v3, uploading the bundle fails with:
```
Upload failed with status 'rejected':
- review-error: Missing required file bundle.yaml in bundle
```
See https://github.com/canonical/iam-bundle/actions/runs/10813501429/job/29997679447#step:6:64
This PR fixes it by including the bundle file in the build directory.
=> ci: fix publish and release action

.github/workflows/tests.yaml
The integration tests started to fail: [1](https://github.com/canonical/iam-bundle/actions/runs/10869368917/job/30185623281), [2](https://github.com/canonical/iam-bundle/actions/runs/10899292374/job/30244367240)
From my local environment where the tests run successfully I infer that the pinned juju agent version is causing this.
This PR unpins the `3.4.0` agent version, so that the latest stable one is used.
=> ci: unpin juju agent version

bundle.yaml.j2
see https://github.com/canonical/postgresql-k8s-operator/issues/701
=> chore: enable postgresql `pg_trgm` and `btree_gin` plugins

bundle.yaml.j2
Change docs link to the discourse index page to have it included on CharmHub (see https://juju.is/docs/sdk/add-docs-to-your-charmhub-page#bundle).
=> chore: link to docs index page

bundle.yaml.j2
This pull request tries to upgrade the hydra since it needs to use the latest version with https://github.com/canonical/hydra-operator/pull/208
=> fix: upgrade the hydra charm version to resolve the integration test failure

.github/workflows/publish.yaml
This pull request aims to add a manual trigger for publishing the bundle because previously it stopped you from publishing the bundle again after the PR was merged and the publish workflow failed (The publish workflow only could be triggered if the bundle.yaml file was modified).
=> ci: add the manual trigger for release the bundle

bundle_renderer.py
Add the `istio` channel to the regex pattern to allow rendering `istio` channel bundle file.
=> fix: allow render bundle for istio channel
